export default {
  type: 'document',
  name: 'investment',
  title: 'Investment',
  fields: [
    {
      name: 'title',
      type: 'string',
      title: 'Title'
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'The slug for the investment. This can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96
      }
    },
    {
      name: 'logo',
      type: 'defaultImage',
      title: 'Logo'
    },
    {
      name: 'logoShouldTakeFullWidth',
      type: 'boolean',
      title: 'Logo should take full width',
      description: 'If set to true, the logo will take the full width of the container.',
      initialValue: false
    },
    {
      name: 'url',
      type: 'url',
      title: 'URL'
    },
    {
      name: 'location',
      type: 'reference',
      title: 'Location',
      to: [{ type: 'location' }]
    },
    {
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'investmentCategory' }]
    },
    {
      name: 'shortDescription',
      type: 'text',
      title: 'Short Description'
    },
    {
      name: 'description',
      type: 'blockContent',
      title: 'Description'
    },
    {
      name: 'exitDate',
      type: 'date',
      title: 'Exit Date',
      options: {
        dateFormat: 'YYYY-MM-DD',
        calendarTodayLabel: 'Today'
      }
    }
  ]
}