export default {
  type: 'document',
  name: 'investment',
  title: 'Investment',
  fields: [
    {
      name: 'title',
      type: 'string',
      title: 'Title'
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'The slug for the investment. This can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      }
    },
    {
      name: 'logo',
      type: 'defaultImage',
      title: 'Logo'
    },
    {
      name: 'url',
      type: 'url',
      title: 'URL'
    },
    {
      name: 'location',
      type: 'reference',
      title: 'Location',
      to: [{ type: 'location' }]
    },
    {
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'investmentCategory' }]
    },
    {
      name: 'shortDescription',
      type: 'blockContent',
      title: 'Short Description'
    },
    {
      name: 'description',
      type: 'blockContent',
      title: 'Description'
    }
  ]
}