export default {
  type: 'document',
  name: 'newsArticle',
  title: 'News Article',
  fields: [
    {
      name: 'title',
      type: 'string',
      title: 'Title'
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'The slug for the article. This can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      }
    },
    {
      name: 'image',
      type: 'defaultImage',
      title: 'Image'
    },
    {
      name: 'shortDescription',
      type: 'blockContent',
      title: 'Short Description'
    },
    {
      name: 'description',
      type: 'blockContent',
      title: 'Description'
    }
  ]
}